app/models/UserModel.py
from app import db
from .camera import BaseModel


class User(BaseModel,db.Model):

    __tablename__ = "users"
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64),unique=True,index=True)
    password = db.Column(db.String(64),nullable=True)
    email = db.Column(db.String(64),unique=True)
    role_id = db.Column(db.Integer,db.ForeignKey("roles.id"))

    def __repr__(self):
        return "<User {}>".format(self.username)

class Role(BaseModel,db.Model):

    __tablename__= "roles"
    id = db.Column(db.Integer,primary_key=True)
    rolename = db.Column(db.String(64),unique=True,index=True)
    users = db.relationship("User",backref="role",lazy="dynamic")

    def __repr__(self):
        return "<Role {}>".format(self.rolename)

app/models/camera.py
from app import db
from datetime import datetime

class BaseModel(object):
    """模型基类，为每个模型补充创建时间与更新时间"""

    create_time = db.Column(db.DateTime, default=datetime.now)  # 记录的创建时间
    update_time = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)  # 记录的更新时间

class Camera(BaseModel,db.Model):
    __tablename__ = "camera"
    CameraId = db.Column(db.Integer, primary_key=True)
    CameraName = db.Column(db.String(64),unique=True,nullable=False)
    CameraIp = db.Column(db.String(32),nullable=False)
    CameraPort = db.Column(db.Integer,nullable=False)
    CameraAccount = db.Column(db.String(64))
    CameraPassWord = db.Column(db.String(32),nullable=False)
    CameraDesc = db.Column(db.String(128))
    CameraStatus = db.Column(db.Integer)

class Area(BaseModel,db.Model):
    __tablename__ = "area"
    AreaId = db.Column(db.Integer,primary_key=True)
    AreaName = db.Column(db.String(32))
    AreaDesc = db.Column(db.String(128))
    ParentId = db.Column(db.Integer)
    IsDelete = db.Column(db.Boolean)

    # camera = db.relationship("Camera",backref="area")

app/__init__.py
import os
from flask import Flask,request
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect
from werkzeug.utils import import_string
from config import config,baseconfig
from flask_moment import Moment
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from celery import Celery


mail = Mail()
moment = Moment()
db = SQLAlchemy()
csrf = CSRFProtect()
bootstrap = Bootstrap()

celery = Celery(__name__,backend=baseconfig.CELERY_RESULT_BACKEND,broker=baseconfig.CELERY_BROKER_URL)

def create_app(config_name):

    # 参加Flask应用程序实例
    app = Flask(__name__)
    config_mode = config[config_name]
    app.config.from_object(config_mode)
    db.init_app(app)
    csrf.init_app(app)
    moment.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)
    celery.conf.update(app.config)
    filenames = os.listdir("app/resources")
    for filename in filenames:
        if os.path.isdir("app/resources/"+filename) and os.path.exists('app/resources/'+filename+'/__init__.py'):
            bp = import_string('app.resources.'+filename+':'+filename)
            app.register_blueprint(bp)
    return app,db

app/resources/dashboard/__init__.py
# coding=utf-8

from flask import Blueprint
from flask import render_template

#: 初始化Main蓝图. 注意静态文件和模板文件夹路径
#: 模板路径是 root_path + template_folder
#: root_path 是 blueprintdemo的路径

dashboard = Blueprint('dashboard', __name__,url_prefix="/api/dashboard")

from . import view1

app/resources/device/__init__.py
# coding=utf-8

from flask import Blueprint
from flask import render_template

#: 初始化Main蓝图. 注意静态文件和模板文件夹路径
#: 模板路径是 root_path + template_folder
#: root_path 是 blueprintdemo的路径

device = Blueprint('device', __name__,url_prefix="/api/device")

app/resources/monitor/__init__.py
# coding=utf-8

from flask import Blueprint
from flask import render_template

#: 初始化Main蓝图. 注意静态文件和模板文件夹路径
#: 模板路径是 root_path + template_folder
#: root_path 是 blueprintdemo的路径

monitor = Blueprint('monitor', __name__,url_prefix="/api/monitor")

app/resources/task/__init__.py
# coding=utf-8

from flask import Blueprint
from flask import render_template

#: 初始化Main蓝图. 注意静态文件和模板文件夹路径
#: 模板路径是 root_path + template_folder
#: root_path 是 blueprintdemo的路径

task = Blueprint('task', __name__,url_prefix="/api/task")

app/resources/user/__init__.py
# coding=utf-8

from flask import Blueprint
from flask import render_template

#: 初始化Main蓝图. 注意静态文件和模板文件夹路径
#: 模板路径是 root_path + template_folder
#: root_path 是 blueprintdemo的路径

user = Blueprint('user', __name__,url_prefix="/api/user",template_folder="templates")
from . import views
from . import viewtwo
from . import userfilter

app/resources/user/views.py
from . import user
from flask import render_template, redirect, url_for, request, sessions, make_response, abort
from datetime import datetime


@user.route('/')
def index():
    abort(404)
    return "hello"

@user.errorhandler(404)
def nofound(e):
    print("nodata")
    return render_template("user/error.html",current=datetime.utcnow()), 404

@user.route("/redirect")
def redirects():
    return redirect(url_for("user.index"))

@user.route("/hello/<string:name>/")
def helloindex(name):
    return "hello {}".format(name)


@user.route("/temp")
def template():
    return render_template("user/index.html", current_time = datetime.utcnow())

app/resources/video/__init__.py
# coding=utf-8

from flask import Blueprint
from flask import render_template

#: 初始化Main蓝图. 注意静态文件和模板文件夹路径
#: 模板路径是 root_path + template_folder
#: root_path 是 blueprintdemo的路径

video = Blueprint('video', __name__,url_prefix="/api/video")

app/templates/mail_tem/html/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
<h1>
    hello guys
</h1>
<hr>
{#hello welcome#}
{{ user }} welcome you

</body>
</html>

app/templates/user/error.html
<!DOCTYPE html>

<html lang="en">
{#<script>{{ moment.include_moment() }}</script>#}
<head>
    <meta charset="UTF-8">
    <title>404</title>
</head>
<body>
this is the error page! please hold on!
 <a href="{{ url_for("user.helloindex",name="ingin",_external=True) }}">click here</a>
<p>current time is {{ moment(current).format("LLL") }}.</p>
<P>That was {{ moment(current).fromNow(refresh=True) }}</P>
</body>
</html>

app/templates/user/index.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang('zh-CN') }}
{% endblock %}
{% block title %}flasky{% endblock %}
{% block content %}
{#<p>现在时间时: {{ moment().format('YYYY年M月D日, h:mm:ss a') }}.</p>#}
{#<p>已经过去了: {{ moment().fromTime(time) }}.</p>#}
{#<p>{{ moment().calendar() }}.</p>#}
    <p>The local date and time is {{ moment(current_time).format('LLL') }}.</p>
<p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>
    <p>{{ current_time }}</p>
    <hr>
    <div class="container">
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
<button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
</div>
    {% endfor %}
    </div>

    
    <h1>hello,{% if name %}{{ name }}
            {% else %}please login
        {% endif %}
    </h1>
    <h1>
    {% if known %}
    <p>welcome back</p>
        {% else %}
        <p>pleased to meet you</p>
    {% endif %}
    </h1>
    {{ wtf.quick_form(form) }}

{% endblock %}

app/templates/user/ttsafe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% autoescape false %}
{{ name  }}
{% endautoescape %}
<hr>

{{ ll | one}}
{{ ll | lst }}
</body>
</html>